version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  php:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.php

  nginx:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.nginx
    ports:
      - "80:80"

